services:
  nanopi-neo:
    privileged: true
    restart: no

    build:
      context: .
      network: host

    volumes:
      - ./src:/src:ro
      - ./out_image:/out_image:rw
      - out:/out:rw
      - build:/build:rw

volumes:
  out:
  build:
